import socket
from struct import pack

# k = pack('BBI', 0x01, 0x10, 4)
k = """\
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
fishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonesfishbonefishbonefishbonefishbones
""".encode()
with open('url.txt') as f:
    url = f.readline()
url = '192.168.0.203'
port = 8192
buffer_size = 1024
server_loc = (url, port)

udp_client_socket = socket.socket(family=socket.AF_INET, type=socket.SOCK_DGRAM)
udp_client_socket.sendto(k, server_loc)
server_msg = udp_client_socket.recvfrom(buffer_size)
print(server_msg)